# Generated by Django 5.0.7 on 2024-07-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("wins", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("division", models.CharField(max_length=100)),
                ("conference", models.CharField(max_length=100)),
                ("logo_path", models.CharField(max_length=255)),
            ],
        ),
    ]
